# Generated by Django 4.2 on 2026-01-20 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addsomething',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.TextField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addsomething', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
